# -*- coding: utf-8 -*-
"""Final-Batch_B6_2022_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEHntkVR93zOmjD7eim3id5AwXB8wcvs
"""

!pip install -q transformers torch scikit-learn xgboost pandas numpy nltk

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import re
import os
import nltk
import warnings

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report
from torch.utils.data import DataLoader, TensorDataset
from torch.optim import AdamW
from transformers import AutoTokenizer, AutoModelForSequenceClassification, get_linear_schedule_with_warmup
from xgboost import XGBClassifier
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # setting up of gpu

nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('stopwords')

"""1. Data Collection"""

df = pd.read_csv("/content/Symptom2Disease.csv")

df

"""2. Preprocessing"""

lemmatizer = WordNetLemmatizer()

def clean_text_advanced(text):
    text = str(text).lower()
    text = re.sub(r"[^a-z ]", " ", text)
    text = re.sub(r'\s+', ' ', text).strip()
    words = text.split()
    words = [lemmatizer.lemmatize(w) for w in words]
    return " ".join(words)

df["clean_text"] = df["text"].apply(clean_text_advanced)

"""Encodes categorical text labels into numeric class IDs"""

le = LabelEncoder()
df["y"] = le.fit_transform(df["label"])
num_classes = len(le.classes_)
num_classes

X_train, X_test, y_train, y_test = train_test_split(
    df["clean_text"], df["y"],
    test_size=0.2,
    random_state=42,
    #Balance clas distribution
    stratify=df["y"]
)

"""3. Feature Encoding & Gradient Boosting

*BioBert* *Model*
"""

model_name = "dmis-lab/biobert-base-cased-v1.1"
tokenizer = AutoTokenizer.from_pretrained(model_name)
biobert = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_classes
)
biobert.to(device)

"""Convert text into token tensors, bundle them with labels, and load them in batches for training."""

def tokenize_batch(texts):
    return tokenizer(
        list(texts),
        padding=True,
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )

train_enc = tokenize_batch(X_train)
test_enc = tokenize_batch(X_test)

train_dataset = TensorDataset(train_enc["input_ids"], train_enc["attention_mask"], torch.tensor(y_train.values))
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)

"""focal loss for handling class imbalance and sets up AdamW with a learning-rate scheduler to train the BioBERT model effectively."""

#how mistakes are calculated
#how weights update
def focal_loss(logits, targets, alpha=1, gamma=2):
    ce_loss = F.cross_entropy(logits, targets, reduction='none')
    pt = torch.exp(-ce_loss)
    loss = (alpha * (1 - pt) ** gamma * ce_loss).mean()
    return loss

optimizer = AdamW(biobert.parameters(), lr=2e-5, weight_decay=0.01)
epochs = 10
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=len(train_loader)*epochs)

"""PATH - A

BIOBERT Traning
"""

#trains BioBERT model by repeatedly feeding batches of text,
#computing prediction errors with focal loss, updating weights using the optimizer, and adjusting the learning rate over multiple epochs
biobert.train()
print(f"Training BioBERT for {epochs} epochs...")
for epoch in range(epochs):
    total_loss = 0
    for batch in train_loader:
        optimizer.zero_grad()
        input_ids, attn, labels = [b.to(device) for b in batch]
        outputs = biobert(input_ids=input_ids, attention_mask=attn)
        loss = focal_loss(outputs.logits, labels)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(biobert.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1} Loss: {total_loss/len(train_loader):.4f}")

"""


4. Uncertainty-Aware Prediction"""

#makes multiple predictions
def mc_dropout_predict(model, inputs, T=15):
    model.train()
    preds = []
    with torch.no_grad():
        for _ in range(T):
            outputs = model(**inputs)
            probs = torch.softmax(outputs.logits, dim=1)
            preds.append(probs.cpu().numpy())
    preds = np.array(preds)
    return preds.mean(axis=0), preds.var(axis=0)

"""PATH-B"""

std_stopwords = set(stopwords.words('english'))
negations = {'no', 'not', 'nor', 'neither', 'never'}
custom_stopwords = list(std_stopwords - negations)

tfidf = TfidfVectorizer(max_features=5000, stop_words=custom_stopwords, ngram_range=(1,2))
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

gb_model = XGBClassifier(n_estimators=300, learning_rate=0.05, max_depth=6, eval_metric='mlogloss', use_label_encoder=False)
gb_model.fit(X_train_tfidf, y_train)

test_inputs_bert = {k: v.to(device) for k, v in test_enc.items()}
bert_probs, bert_var = mc_dropout_predict(biobert, test_inputs_bert)
gb_probs = gb_model.predict_proba(X_test_tfidf)

final_probs = 0.6 * bert_probs + 0.4 * gb_probs
final_preds = final_probs.argmax(axis=1)

print(f"FINAL ACCURACY: {accuracy_score(y_test, final_preds)*100:.2f}%")

from sklearn.metrics import classification_report

# 1. Get the class names from the LabelEncoder
target_names = le.classes_

# 2. Generate the report
# Note: final_preds and y_test are already defined in your Cell [15]
report = classification_report(y_test, final_preds, target_names=target_names)

print("Ensemble Model Classification Report:\n")
print(report)

"""Temperature scaling is used to calibrate predicted probabilities by adjusting model confidence without affecting accuracy."""

#how confident a model’s probabilities are without changing its predictions.
class ModelWithTemperature(nn.Module):
    """
    A thin wrapper around a model that performs temperature scaling on its outputs.
    """
    def __init__(self, model):
        super(ModelWithTemperature, self).__init__()
        self.model = model
        self.temperature = nn.Parameter(torch.ones(1) * 1.5) # Initialize T > 1 for potentially under-confident models

    def forward(self, input_ids, attention_mask):
        logits = self.model(input_ids=input_ids, attention_mask=attention_mask).logits
        return logits / self.temperature

calibrated_biobert = ModelWithTemperature(biobert).to(device)

calibration_dataset = TensorDataset(test_enc["input_ids"], test_enc["attention_mask"], torch.tensor(y_test.values))
calibration_loader = DataLoader(calibration_dataset, batch_size=16, shuffle=False)

optimizer_temp = torch.optim.LBFGS([calibrated_biobert.temperature], lr=0.01, max_iter=50)

def _eval_loss_and_opt():
    optimizer_temp.zero_grad()
    for batch in calibration_loader:
        input_ids, attn, labels = [b.to(device) for b in batch]
        logits = calibrated_biobert(input_ids=input_ids, attention_mask=attn)
        loss = nn.CrossEntropyLoss()(logits, labels)
        loss.backward()
    return loss

print("Optimizing temperature...")
optimizer_temp.step(_eval_loss_and_opt)

optimized_temperature = calibrated_biobert.temperature.item()
print(f"Optimized Temperature: {optimized_temperature:.4f}")

"""5. Fusion & Calibration"""

#takes a symptom description and returns a final disease prediction with confidence and uncertainty using your calibrated BioBERT + XGBoost ensemble.
def predict_disease_calibrated(symptom_text):
    clean_input = clean_text_advanced(symptom_text)

    inputs = tokenizer(clean_input, return_tensors="pt", truncation=True, padding=True, max_length=128).to(device)

    calibrated_biobert.eval()
    with torch.no_grad():
        logits = calibrated_biobert.model(**inputs).logits / optimized_temperature
        bert_mean = torch.softmax(logits, dim=1).cpu().numpy()


        _, bert_v = mc_dropout_predict(biobert, inputs)

    bert_pred_idx = bert_mean[0].argmax()
    bert_conf = bert_mean[0][bert_pred_idx]
    bert_disease = le.inverse_transform([bert_pred_idx])[0]

    tfidf_vec = tfidf.transform([clean_input])
    gb_p = gb_model.predict_proba(tfidf_vec)[0]
    gb_pred_idx = gb_p.argmax()
    gb_conf = gb_p[gb_pred_idx]
    gb_disease = le.inverse_transform([gb_pred_idx])[0]

    fused = 0.6 * bert_mean[0] + 0.4 * gb_p
    pred_idx = fused.argmax()
    disease = le.inverse_transform([pred_idx])[0]
    conf = fused[pred_idx]

    raw_u = bert_v.max()
    uncertainty_score = (raw_u - u_min) / (u_max - u_min + 1e-9)
    uncertainty_score = max(0.0, min(1.0, uncertainty_score))

    debug_info = {
        "Cleaned_Input": clean_input,
        "BioBERT_Calibrated": f"{bert_disease} ({bert_conf:.2f})",
        "XGBoost": f"{gb_disease} ({gb_conf:.2f})",
        "Match": bert_disease == gb_disease
    }

    return disease, conf, uncertainty_score, debug_info

if 'bert_var' in globals():
    u_min = bert_var.min()
    u_max = bert_var.max()
else:
    u_min = 0.0
    u_max = 1.0

new_symptom_to_validate = "high fever, severe headache, eye pain, muscle/joint pain, nausea, fatigue, and sometimes rash or bleeding signs"

d, c, u, debug = predict_disease_calibrated(new_symptom_to_validate)

print(f"\nInput Symptom: '{new_symptom_to_validate}'")
print(f"  -> Predicted Disease: {d}")
print(f"  -> Confidence: {c*100:.2f}%")
print(f"  -> Uncertainty: {u:.4f} ")

if c < 0.50:
    print("  ⚠️ Prediction Flagged (Low Confidence)")
elif u > 0.80:
    print("  ⚠️ Prediction Flagged (High Uncertainty)")
else:
    print("  ✅ Prediction Accepted")

!pip install -q sentence-transformers

"""6. Query Vectorization"""

from sentence_transformers import SentenceTransformer
from datasets import load_dataset
from sklearn.metrics.pairwise import cosine_similarity

def formulate_clinical_query(diagnosis):
    return f"clinical case of {diagnosis}"
sentence_model = SentenceTransformer('cambridgeltl/BioRedditBERT-uncased')
#sentence_model = SentenceTransformer('all-MiniLM-L6-v2')

sentence_model.to(device)

accepted_diagnosis = d

clinical_query = formulate_clinical_query(accepted_diagnosis)

query_vector = sentence_model.encode(clinical_query, convert_to_tensor=True)
query_vector

"""### Demonstrate Semantic Retrieval with New Corpus

*   List item
*   List item


"""

def retrieve_top_k_dialogues(query_vector, corpus_embeddings, corpus, k=3):
    """
    Calculates cosine similarity, ranks results, and retrieves top-k relevant dialogues.
    """
    query_vector = query_vector.to(device)
    similarities = cosine_similarity(query_vector.cpu().numpy().reshape(1, -1), corpus_embeddings.cpu().numpy())
    similarities = similarities.flatten()
    sorted_indices = similarities.argsort()[::-1]

    top_k_results = []
    for i in range(k):
        idx = sorted_indices[i]
        top_k_results.append({
            "dialogue": corpus[idx],
            "similarity_score": similarities[idx]
        })
    return top_k_results

print("Similarity scoring and top-k retrieval functions defined.")

"""### Step 9: Retrieval Corpus (MedDialog) & Anonymization (NER)

---



"""

!pip install -q datasets transformers spacy
!python -m spacy download en_core_web_sm

import spacy
from datasets import load_dataset

print("Loading MedDialog Dataset...")
# Use a publicly available MedDialog english subset or medical dialogs dataset
# We use 'medical_dialog' from huggingface which contains patient-doctor conversations.
try:
    # 1. Load a modern, robust, script-free Medical QA dataset
    med_dialog_dataset = load_dataset("keivalya/MedQuad-MedicalQnADataset", split="train[:5000]")

    # 2. Re-map the columns from 'Question'/'Answer' to 'patient'/'doctor'
    # so it plugs perfectly into our existing pipeline!
    def map_columns(example):
        return {
            "patient": example["Question"],
            "doctor": example["Answer"]
        }

    med_dialog_dataset = med_dialog_dataset.map(map_columns)
    print("MedQuad Dataset loaded and formatted successfully!")

except Exception as e:
    print(f"Dataset load failed: {e}. Falling back to mock data for demonstration.")
    med_dialog_dataset = [
        {"patient": "I have a severe headache and high fever.", "doctor": "Take ibuprofen and rest. You may have a viral infection."},
        {"patient": "I am experiencing muscle pain and fatigue with a rash.", "doctor": "This could be dengue. Stay hydrated and monitor your platelets."}
    ]


# Load NER for Anonymization (Step 2.3)
nlp = spacy.load("en_core_web_sm")

def anonymize_text(text):
    doc = nlp(text)
    anonymized = text
    for ent in doc.ents:
        if ent.label_ in ["PERSON", "GPE", "DATE", "ORG"]:
            anonymized = anonymized.replace(ent.text, f"[{ent.label_}]")
    return anonymized

print("Formatting and anonymizing corpus...")
med_dialog_corpus_enhanced = []
for item in med_dialog_dataset:
    # Handle both real dataset format and our mock fallback format
    patient_text = item.get("patient", item.get("patient_description", ""))
    doctor_text = item.get("doctor", item.get("doctor_response", ""))

    if patient_text and doctor_text:
        anon_patient = anonymize_text(patient_text)
        anon_doctor = anonymize_text(doctor_text)
        combined = f"Patient: {anon_patient}\nDoctor: {anon_doctor}"
        med_dialog_corpus_enhanced.append(combined)

print(f"Enhanced MedDialog corpus created with {len(med_dialog_corpus_enhanced)} entries.")
print("Encoding MedDialog corpus...")
corpus_embeddings_enhanced = sentence_model.encode(med_dialog_corpus_enhanced, convert_to_tensor=True)
corpus_embeddings_enhanced = corpus_embeddings_enhanced.to(device)
print("Corpus encoded successfully!")

"""### Step 10: Treatment Generation using FLAN-T5

"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch
import re
from google import genai

device = "cuda" if torch.cuda.is_available() else "cpu"
generator_model_name = "google/flan-t5-base"

generator_tokenizer = AutoTokenizer.from_pretrained(generator_model_name)
generator_model = AutoModelForSeq2SeqLM.from_pretrained(generator_model_name).to(device)

GEMINI_API_KEY = "AIzaSyAadxGW8GMYsUmEWfPTztaP6wRwsahs79Y"
gemini_client = genai.Client(api_key=GEMINI_API_KEY)

def contains_fake_drug(text):
    fake_keywords = ["magic-cure", "instant-heal", "miracle-drug"]
    return any(fake in text.lower() for fake in fake_keywords)

def generate_treatment(patient_symptoms, diagnosis, top_k_dialogues):
    context = ""
    for idx, res in enumerate(top_k_dialogues):
        clean_snip = res['dialogue'].replace("\n", " ").strip()
        context += f"Evidence {idx+1}: {clean_snip}\n"

    shared_prompt = f"""You are a clinical decision support system. Your goal is to provide a structured treatment plan for the patient based on the provided <evidence>.

    ### CLINICAL CONTEXT:
    - **Patient Symptoms:** {patient_symptoms}
    - **Diagnosis:** {diagnosis}

    ### <evidence>:
    {context if context.strip() else "Standard supportive care for viral infections including hydration and fever management."}

    ### INSTRUCTIONS:
    1. Review the <evidence> to identify medications, dosages, and care protocols.
    2. If the <evidence> is general, provide standard clinical guidelines appropriate for the diagnosis: {diagnosis}.
    3. **REQUIRED FORMAT:**
       Rx: [Medication Name] [Dosage] - [Frequency]
       Advice: [Brief care instructions]
    4. **RESTRICTION:** Do not use any square brackets [ ] or "Insufficient data" messages unless there is a severe safety risk.

    ### OUTPUT:
    """

    inputs = generator_tokenizer(shared_prompt, return_tensors="pt", max_length=1024, truncation=True).to(device)

    with torch.no_grad():
        outputs = generator_model.generate(
            **inputs,
            max_new_tokens=150,
            num_beams=4,
            no_repeat_ngram_size=3,
            early_stopping=False
        )

    generate_treatment = generator_tokenizer.decode(outputs[0], skip_special_tokens=True).strip()
    generate_treatment = re.sub(r'\[.*?\]', '', generate_treatment)
    generate_treatment = re.sub(r'\s+', ' ', generate_treatment).strip()

    if len(generate_treatment) > 800 or "cancer" in generate_treatment.lower() or "pregnancy" in generate_treatment.lower() or contains_fake_drug(generate_treatment):
        generate_treatment = "Rx: Paracetamol 500mg as needed for pain/fever. Rest and adequate hydration. Seek specialist consultation."

    response = gemini_client.models.generate_content(
        model='gemini-2.5-flash',
        contents=shared_prompt,
        config=genai.types.GenerateContentConfig(
            temperature=0.2,
            max_output_tokens=200
        )
    )

    generatetreatment1 = response.text
    generatetreatment1 = re.sub(r'\[.*?\]', '', generatetreatment1)
    generatetreatment1 = re.sub(r'\s+', ' ', generatetreatment1).strip()

    if len(generatetreatment1) > 800 or "cancer" in generatetreatment1.lower() or "pregnancy" in generatetreatment1.lower() or contains_fake_drug(generatetreatment1):
        generatetreatment1 = "Rx: Paracetamol 500mg as needed for pain/fever. Rest and adequate hydration. Seek specialist consultation."

    return generatetreatment1

"""### Step 11: Safety Validation (Antibiotic Stewardship & RxNorm DDI)



"""

import requests
import re
import spacy

# Ensure spacy model is loaded (handles the case if it's missing in the environment)
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    print("Downloading spacy model...")
    import os
    os.system("python -m spacy download en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")

print("Initializing Safety Validation Module (RxNorm & Stewardship)...")



def extract_medications(text):
    """Extracts potential medication names from the generated text."""
    # Expanded to include a few more common drugs for better mock extraction
    common_drugs = [
        "ibuprofen", "paracetamol", "amoxicillin", "penicillin", "aspirin",
        "azithromycin", "doxycycline", "ciprofloxacin", "tylenol", "omeprazole",
        "metformin", "lisinopril", "atorvastatin"
    ]
    drugs = []
    # Clean text and split
    words = [re.sub(r'[^a-z]', '', word.lower()) for word in text.split()]
    for word in words:
        if word in common_drugs:
            drugs.append(word)
    return list(set(drugs))

def check_rxnorm_ddi(drugs):
    """
    Screens recommendations via the RxNorm database to detect potential
    drug-drug interactions (Outputs DDI_risk score).
    """
    if len(drugs) < 2:
        return "No DDI risk detected (0-1 drugs identified).", 0.0

    rxcuis = []
    for drug in drugs:
        try:
            # UPDATE: Added 5-second timeout to prevent notebook freezing
            res = requests.get(f"https://rxnav.nlm.nih.gov/REST/rxcui.json?name={drug}", timeout=5)
            if res.status_code == 200:
                data = res.json()
                if "idGroup" in data and "rxnormId" in data["idGroup"]:
                    rxcuis.append(data["idGroup"]["rxnormId"][0])
        except requests.exceptions.RequestException:
            continue # Skip gracefully on API timeout/error

    if len(rxcuis) < 2:
        return "Insufficient RxCUI mappings for interaction check.", 0.0

    cui_list = "+".join(rxcuis)
    try:
        res = requests.get(f"https://rxnav.nlm.nih.gov/REST/interaction/list.json?rxcuis={cui_list}", timeout=5)
        if res.status_code == 200 and "fullInteractionTypeGroup" in res.json():
            # UPDATE: Explicitly returning 1.0 risk score and matching paper terminology
            return "⚠️ FLAGGED FOR PHARMACIST REVIEW: Potential Drug-Drug Interaction detected.", 1.0
    except requests.exceptions.RequestException:
        return "RxNorm API unavailable. Proceed with caution.", 0.0

    return "✅ Passed RxNorm DDI Screening.", 0.0

def check_antibiotic_stewardship(drugs):
    """
    Treatments violating antimicrobial stewardship rules are automatically flagged
    using the NLM RxClass API (Outputs AS_violation score).
    """
    if not drugs:
        return "✅ Passed Antibiotic Stewardship.", 0.0

    flagged_antibiotics = []

    for drug in drugs:
        # Ignore generic safe keywords that might slip through your extractor
        if drug in ["antibiotic", "antibiotics"]:
            flagged_antibiotics.append(drug)
            continue

        try:
            # 1. Get the RxCUI for the drug (Same as your DDI check)
            res = requests.get(f"https://rxnav.nlm.nih.gov/REST/rxcui.json?name={drug}", timeout=5)
            if res.status_code == 200:
                data = res.json()
                if "idGroup" in data and "rxnormId" in data["idGroup"]:
                    rxcui = data["idGroup"]["rxnormId"][0]

                    # 2. Query the RxClass API for the drug's pharmacological class (EPC)
                    class_res = requests.get(
                        f"https://rxnav.nlm.nih.gov/REST/rxclass/class/byRxcui.json?rxcui={rxcui}&relaSource=EPC",
                        timeout=5
                    )

                    if class_res.status_code == 200:
                        class_data = class_res.json()
                        if "rxclassDrugInfoList" in class_data:
                            # 3. Check if any of the classes indicate it is an antibiotic
                            for info in class_data["rxclassDrugInfoList"]["rxclassDrugInfo"]:
                                class_name = info["rxclassMinConceptItem"]["className"].lower()
                                if "anti-bacterial" in class_name or "antibacterial" in class_name or "antibiotic" in class_name:
                                    flagged_antibiotics.append(drug)
                                    break # Found a match, stop checking classes for this drug
        except requests.exceptions.RequestException:
            continue # Skip gracefully on API timeout/error

    if flagged_antibiotics:
        return f"⚠️ FLAGGED: Antibiotic use detected ({', '.join(flagged_antibiotics)}). Enforce stewardship rules.", 1.0

    return "✅ Passed Antibiotic Stewardship.", 0.0

def safety_validation(treatment_plan):
    """Main function to run all safety checks on the generated plan."""
    extracted_drugs = extract_medications(treatment_plan)

    # Calculate DDI_risk and AS_violation penalties
    ddi_msg, ddi_risk = check_rxnorm_ddi(extracted_drugs)
    abx_msg, as_violation = check_antibiotic_stewardship(treatment_plan)

    # UPDATE: If either risk score is triggered, the recommendation is considered unsafe
    is_safe = (ddi_risk == 0.0) and (as_violation == 0.0)

    # UPDATE: Returning a structured dictionary makes it much easier to plug into the Gradio UI
    return {
        "is_safe": is_safe,
        "extracted_drugs": extracted_drugs,
        "ddi_message": ddi_msg,
        "stewardship_message": abx_msg
    }

print("Safety Validation functions defined and aligned with SCGS constraints.")

"""### Step 12: Web User Interface (Gradio)

"""

!pip install -q gradio

import gradio as gr
import traceback

def generate_full_html_report(symptoms):
    if not symptoms.strip():
        return "<div style='min-height: 40px;'></div>"

    try:
        # --- 1. Classification (BioBERT + MC Dropout) ---
        diagnosis, conf, uncertainty, _ = predict_disease_calibrated(symptoms)

        # Ensure percentages are handled correctly (0.85 -> 85.0)
        conf_pct = float(conf) if conf > 1.0 else float(conf * 100)

        # --- THE CLINICAL CIRCUIT BREAKER ---
        # If confidence is below 50%, the system refuses to generate treatment.
        if conf_pct < 50.0:
            safe_diagnosis = diagnosis.replace('"', '&quot;').replace("'", "&#39;").title()
            warning_html = "<p style='color: #c62828; font-weight: bold;'>⚠️ Low confidence – refer to medical expert</p>"

            # Circuit Breaker Treatment Message
            safe_treatment = (
                "<span style='color: #c62828; font-weight: bold;'>⚠️ GENERATION HALTED:</span> "
                "Diagnostic confidence is below the safe threshold (50%). Generating a treatment plan "
                "for an uncertain diagnosis is unsafe. Patient must be referred to a human specialist."
            )

            # Circuit Breaker Safety Message
            safety_html = (
                "<div style='background: #ffebee; padding: 10px; border-left: 4px solid #c62828;'>"
                "<strong style='color:#c62828;'>Safety Logic Halted:</strong> Validation bypassed "
                "to prevent processing an uncertain diagnosis.</div>"
            )

        else:
            # --- Proceed Normally for High Confidence Cases ---
            warning_html = "<p style='color: #2e7d32; font-weight: bold;'>✅ Safe confidence level for preliminary guidance</p>"

            # 2. Retrieval (RAG)
            clinical_query = f"clinical case of {diagnosis}"
            query_vec = sentence_model.encode(clinical_query, convert_to_tensor=True)
            top_k = retrieve_top_k_dialogues(query_vec, corpus_embeddings_enhanced, med_dialog_corpus_enhanced, k=5)

            # 3. Treatment Generation (FLAN-T5)
            treatment = generate_treatment(symptoms, diagnosis, top_k)

            # 4. Safety Validation (RxNorm + Stewardship)
            safety_results = safety_validation(treatment)

            # Build Safety HTML
            safety_html = "<p style='font-size: 14px; margin-bottom: 15px;'>Evaluated against RxNorm and Antimicrobial Stewardship (AS) rules.</p>"

            # DDI Check UI
            if "FLAGGED" in safety_results['ddi_message']:
                safety_html += f"<div style='background: #ffebee; padding: 10px; border-left: 4px solid #c62828; margin-bottom: 10px;'><strong style='color:#c62828;'>RxNorm DDI:</strong> {safety_results['ddi_message']}</div>"
            elif "unavailable" in safety_results['ddi_message'].lower():
                safety_html += f"<div style='background: #fff3e0; padding: 10px; border-left: 4px solid #ff8f00; margin-bottom: 10px;'><strong style='color:#ef6c00;'>RxNorm DDI:</strong> Service Unavailable</div>"
            else:
                safety_html += f"<div style='background: #e8f5e9; padding: 10px; border-left: 4px solid #2e7d32; margin-bottom: 10px;'><strong style='color:#2e7d32;'>RxNorm DDI:</strong> {safety_results['ddi_message']}</div>"

            # Stewardship UI
            if "FLAGGED" in safety_results['stewardship_message']:
                safety_html += f"<div style='background: #fff3e0; padding: 10px; border-left: 4px solid #ff8f00; margin-bottom: 10px;'><strong style='color:#ef6c00;'>Stewardship:</strong> {safety_results['stewardship_message']}</div>"
            else:
                safety_html += f"<div style='background: #e8f5e9; padding: 10px; border-left: 4px solid #2e7d32; margin-bottom: 10px;'><strong style='color:#2e7d32;'>Stewardship:</strong> {safety_results['stewardship_message']}</div>"

            # Extracted Drugs Badge (Visual Polish)
            drugs_list = ", ".join(safety_results['extracted_drugs']).title() if safety_results['extracted_drugs'] else "None detected"
            safety_html += f"<div style='margin-top: 10px;'><span style='background-color: #f0f0f0; padding: 4px 10px; border-radius: 4px; font-size: 13px;'><strong>Parsed Medications:</strong> {drugs_list}</span></div>"

            safe_diagnosis = diagnosis.replace('"', '&quot;').replace("'", "&#39;").title()
            safe_treatment = treatment.replace('"', '&quot;').replace("'", "&#39;").replace('\n', '<br/>')

        # --- Dashboard Layout ---
        html_content = f"""
        <div style="font-family: 'Segoe UI', sans-serif; background: transparent;">
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 10px;">
                <div style="background: white; padding: 25px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
                    <h3 style="margin-top: 0; color: #006064; font-size: 1.1rem; margin-bottom: 20px;">Prediction Summary</h3>
                    <p style="font-size: 15px; margin: 0; color: #666;">Predicted Disease:</p>
                    <p style="font-size: 18px; margin: 5px 0 20px 0; color: #000; font-weight: bold;">{safe_diagnosis}</p>
                    <p style="font-size: 14px; margin: 0; color: #666;">System Confidence:</p>
                    <h2 style="font-size: 32px; font-weight: bold; color: #2e7d32; margin: 0 0 10px 0;">{conf_pct:.1f}%</h2>
                    {warning_html}
                </div>
                <div style="background: white; padding: 25px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
                    <h3 style="margin-top: 0; color: #006064; font-size: 1.1rem; margin-bottom: 15px;">Safety & Reliability</h3>
                    {safety_html}
                </div>
                <div style="background: white; padding: 25px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); grid-column: 1 / -1;">
                    <h3 style="margin-top: 0; color: #006064; font-size: 1.1rem; margin-bottom: 15px;">Clinical Treatment Option</h3>
                    <p style="font-size: 15px; margin: 0; color: #333; line-height: 1.6;">{safe_treatment}</p>
                </div>
            </div>
        </div>
        """
        return html_content

    except Exception as e:
        error_msg = str(e).replace('"', '&quot;').replace("'", "&#39;")
        return f"<div style='background: #ffebee; padding: 20px; border-radius: 8px; border-left: 5px solid #c62828;'><strong>System Error:</strong> {error_msg}</div>"

# CSS remains the same as your provided code
custom_css = """
body, .gradio-container { background: linear-gradient(120deg, #e0f7fa, #ffffff) !important; color: #333 !important; }
.gradio-container { max-width: 1000px !important; margin: 0 auto !important; padding: 40px 20px !important; border: none !important;}
.input-card { background: white !important; padding: 25px !important; border-radius: 8px !important; box-shadow: 0 4px 6px rgba(0,0,0,0.1) !important; }
.submit-btn { background-color: #00695c !important; color: white !important; font-weight: bold !important; border-radius: 6px !important; }
footer.svelte-1rjryqp { display: none !important; }
"""

with gr.Blocks(css=custom_css, title="A SAFETY-SENSITIVE AND UNCERTAINTY-AWARE CLINICAL DECISION SUPPORT FRAMEWORK USING BIO-BERT AND RETRIEVAL-AUGMENTED FLAN-T5") as demo:
    gr.HTML("""
        <div style='text-align: center; margin-bottom: 30px;'>
            <h2 style='color: #006064; margin-bottom: 5px;'>🩺 A SAFETY-SENSITIVE AND UNCERTAINTY-AWARE CLINICAL DECISION SUPPORT FRAMEWORK USING BIO-BERT AND RETRIEVAL-AUGMENTED FLAN-T5</h2>
        </div>
    """)
    with gr.Column(elem_classes="input-card"):
        symptom_input = gr.Textbox(lines=4, show_label=False, placeholder="Describe patient symptoms...")
        submit_btn = gr.Button("Analyze Case", elem_classes="submit-btn")
    dashboard_html = gr.HTML("<div style='min-height: 40px;'></div>")
    submit_btn.click(fn=generate_full_html_report, inputs=symptom_input, outputs=dashboard_html)
    gr.HTML("<footer style='text-align: center; margin-top: 40px; color: #666;'>Final Year Project | (Batch B6)</footer>")

demo.launch(share=True)

